server:
  port: 83
  servlet:
    context-path: /

# ???A???????
client:
  # ?????
  type: 1
  # ?????
  name: testB
  # ??????
  status: 0
  # ?????
  knowledge: 1

# netty??
netty:
  tcp:
    # ????
    server:
      port: 7001

spring:
  profiles:
    active: redis