#配置spring
spring:
  # redis配置
  redis:
    host: localhost
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 50
        max-wait: 3000
        max-idle: 10
        min-idle: 2
    timeout: 5000
    password: 123456