spring:
  ## 配置数据库
  datasource:
    name: mysql-p6spy
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    #配置数据源
    url: jdbc:p6spy:mysql://localhost:3307/test?useSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-statement-timeout: 100000



